---
version: '2'
services:
  db:
    image: postgres
    container_name: simjam-db
    ports:
      - 5432:5432
    volumes:
      - ./create-schema-data.sql:/tmp/create-schema-data.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8000:8080